### ISSUE TITLE
Unexpected result using --iter==1

### ISSUE THREAD

**Issue by hui-liu** [tanghaibao/jcvi#482] opened 2022-06-24 03:09 UTC
When using the parameter of `--iter==1`, I failed to get synteny genes for a region I was interested in.

![i1](https://user-images.githubusercontent.com/10741007/175453529-bb7cdd98-c5e8-41c6-8b48-ed196b8f38e1.png)

Then I set the parameter of `--iter==2`, and I got the synteny genes for this region.

![i2](https://user-images.githubusercontent.com/10741007/175454046-f316f88a-9bab-4903-986b-e29f1895dbfa.png)

I wondered why I failed to get the synteny genes in this region using `--iter==1`?

Best,
Hui

**Comment by tanghaibao** [comment] 2022-06-24 13:38
@hui-liu 

This is very weird. The way the `--iter` works, it will find the best block that is aligned in terms of score.
There can be situations (for example, inversion) that prevent the second smaller block to be included within a bigger block.
Can you look before and after this region, to see if there are bigger blocks around the region that you show?

Otherwise, I'd be interested to see the data (if you can share it) to make sure this isn't a bug.

**Comment by hui-liu** [comment] 2022-06-25 05:15
Hi,

Thank you for your kind reply.

The attached files are the whole chromosome where the region is located in, including `iter==1` and `iter==2`. I also plot the synteny results (`iter==1`) for the two chromosomes from two speceis (qvar and qmon) using `jcvi.graphics.synteny`.

Here is the command I used:
```
ids=$(sed -n '/QV06G069700.1/,/QV06G097100.1/p' qvar.qmon.i1.chr06.blocks | cut -f 1 | xargs  | sed 's/ /,/g')
python -m jcvi.graphics.synteny qvar.qmon.i1.chr06.blocks my.bed qvar.qmon.i1.chr06.blocks.layout \
--glyphstyle=arrow --genelabelsize 3  \
--genelabels $ids
```

We can see that the synteny genes were absent in the region (I have added the labels in this regions in the plot. Please see the qvar.qmon.i1.chr06.pdf for detail).

I hope this helps. Thanks.

\# I have added the `.txt` in each plain file for uploading.
\# iter==1
[qvar.qmon.i1.chr06.blocks.txt](https://github.com/tanghaibao/jcvi/files/8983911/qvar.qmon.i1.chr06.blocks.txt)

\# iter==2
[qvar.qmon.i2.chr06.blocks.txt](https://github.com/tanghaibao/jcvi/files/8983912/qvar.qmon.i2.chr06.blocks.txt)

\# bed file
[my.bed.txt](https://github.com/tanghaibao/jcvi/files/8983922/my.bed.txt)

\# Microsynteny visualization
[qvar.qmon.i1.chr06.pdf](https://github.com/tanghaibao/jcvi/files/8983913/qvar.qmon.i1.chr06.pdf)

**Comment by hui-liu** [comment] 2022-07-06 05:58
Hi @tanghaibao, did you have any idea to fix this issue? If you need any extra data, I still can share it with you. Thank you.

**Comment by tanghaibao** [comment] 2022-07-08 04:09
@hui-liu 

Would you mind sending the `qvar.qmon.anchors` file?

**Comment by tanghaibao** [comment] 2022-07-08 04:23
@hui-liu 

Thanks for the data. The issue is that there is a region of tandem duplicated segment (the lower part of the figure below, genome A matches to two adjacent regions in genome B).

<img width="394" alt="image" src="https://user-images.githubusercontent.com/106987/177915727-45fb08f0-fa22-4ba8-8f25-2bad57a09cf2.png">

Unfortunately, this duplicated segment has caused overlaps between the synteny blocks when `--iter=1` is used - resulting in the loss of the synteny block (since the algorithm doesn't know which one is the best scoring one in the presence of a duplication).

It should be clear if you can do a dot plot in this region.

I don't know of a quick fix for this situation though.

**Closed** 2022-07-10 01:22 UTC
