### ISSUE TITLE
Overlapping genes in block output

### ISSUE THREAD

**Issue by mariamarinr** [tanghaibao/jcvi#582] opened 2023-07-24 10:16 UTC
I am trying to make a synteny analysis with 10 different species, however I am facing some overlapping in the genes between different species. In the image you can see the genes belonging to different species where only the T.cacao genes should be. I have changed the blocks.layout file (image below) to try to avoid this issue but I have still not being able to solve it. 

Thank you in advance for your help.

![image](https://github.com/tanghaibao/jcvi/assets/95214356/5646335d-ed42-455b-856d-2103b0deb8ba)

![image](https://github.com/tanghaibao/jcvi/assets/95214356/c96375d5-14af-4c3e-8d98-803cacd25e07)

**Comment by tanghaibao** [comment] 2023-07-25 21:21
@mariamarinr 

This is very weird. 
Would you mind sending a small subset for me to debug?

**Comment by mariamarinr** [comment] 2023-07-26 14:32
Hi Haibao, 

Thanks for the quick reply! Here is a link with a subset you can download: https://cloud.tu-braunschweig.de/s/DL2GYnS5fF9eE2T

Thank you again for your help!

Best, 

Maria

**Comment by tanghaibao** [comment] 2023-07-26 16:59
@mariamarinr 

Thanks. I was able to download a few FASTA and GFF. 
Would you mind also sending the layout file and BED files that you referred to above and the command for me to reproduce this plotting issue?

**Comment by mariamarinr** [comment] 2023-07-27 18:25
@tanghaibao 

Sure! This is the link with the files and the command. But just so you know this is just a subset with the three species I have noticed the overlapping issue. 

https://cloud.tu-braunschweig.de/s/TqN7xgiHdHp6eym

**Comment by tanghaibao** [comment] 2023-08-01 05:34
@mariamarinr 

Thanks for sending the file over for debugging.

The overlapping genes are due to collision in chromosome name. For example, there are multiple `chr3` in the combined BED:

```console
$ grep ^chr3 Tcacaocriollo.Vvinifera.Brapa.Ahalleri.Athaliana.Esalsugineum.Sparvula.Cgrandiflora.Crubella.Bstricta.bed | grep Tc | head
chr3	36403	51192	Tc03v2_t000010.1	0	-
chr3	36403	51192	Tc03v2_t000010.2	0	-
chr3	38546	51192	Tc03v2_t000010.4	0	-
...
$ grep ^chr3 Tcacaocriollo.Vvinifera.Brapa.Ahalleri.Athaliana.Esalsugineum.Sparvula.Cgrandiflora.Crubella.Bstricta.bed | grep VIT | head
chr3	3055	5194	VIT_203s0038g00010.1	0	+
chr3	7115	7422	VIT_203s0038g00020.1	0	+
chr3	26343	40225	VIT_203s0038g00030.1	0	+
```
Since the top panel has the coordinate on chr3, all these genes get plotted over each other.

The solution is to merged the BED with the following command:

```console
$ python -m jcvi.formats.bed merge Tcacaocriollo.bed  Vvinifera.bed ... -o all.bed
$ grep chr3 all.bed | grep Tc | head
Tcacaocriollo_chr3	36403	51192	Tc03v2_t000010.1	0	-
Tcacaocriollo_chr3	36403	51192	Tc03v2_t000010.2	0	-
Tcacaocriollo_chr3	38546	51192	Tc03v2_t000010.4	0	-
```

You can see that now the chromosome name is disambiguated. Use this BED file instead in your earlier command should fix the overlapping issue for you, I think.

<img width="1235" alt="image" src="https://github.com/tanghaibao/jcvi/assets/106987/885c2cda-6356-4259-aad9-e4edd9be74e2">

**Comment by tanghaibao** [comment] 2023-08-01 05:41
Looking at the [wiki](https://github.com/tanghaibao/jcvi/wiki/MCscan-(Python-version)) page again, the instruction for merging BED is outdated - sorry about it - the documentation is now updated to reflect this.

**Comment by mariamarinr** [comment] 2023-08-02 13:54
Hi Haibao, 

It worked! thank you so much for your help! :)

Best, 

Maria

**Closed** 2023-08-02 15:58 UTC
