### ISSUE TITLE
run jcvi.graphics.karyotype wtih three genomes!

### ISSUE THREAD

**Issue by sunnycqcn** [tanghaibao/jcvi#241] opened 2020-05-08 18:23 UTC
Hello Dr. Tang,
When I run MCscan, I met a error about using three genomes. If I run two genomes, L022 and L023, it works well. LREF has different scaffold numbers, 33 scaffolds. L022 and L023 are 20 scaffolds.
could you help me check this error?
Thanks,
Fuyou

 python -m jcvi.graphics.karyotype seqids layout
14:14:58 [base] Load file `layout`
14:14:58 [base] Load file `LREF.bed`
14:14:59 [base] Load file `L022.bed`
14:14:59 [base] Load file `L023.bed`
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 435, in <module>
    main()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 422, in main
    generank=(not opts.basepair),
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 371, in __init__
    tr = Track(root, lo, gap=gap, height=height, lw=lw, draw=False)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/py2/lib/python2.7/site-packages/jcvi/graphics/karyotype.py", line 175, in __init__
    ratio = span / total
ZeroDivisionError: float division by zero

**Comment by tanghaibao** [comment] 2020-05-09 04:51
Duplicate of #240

**Closed** 2020-05-09 04:53 UTC
