### ISSUE TITLE
the difference between MCScanX and MCscan python version

### ISSUE THREAD

**Issue by wuxiaopei0509** [tanghaibao/jcvi#243] opened 2020-05-14 06:55 UTC
Dear Mr Tang
I use MCScanX to ananlyze Synteny and obtain the results. Then I use MCscan python version to visualize . As you know McScanX use blast to analyze similarity however MCscan python version is not . I want to know to whether the gene Synteny results is very different between the two results.
Thanks a lot.

**Comment by tanghaibao** [comment] 2020-06-13 03:48
duplicate of #244

**Closed** 2020-06-13 03:49 UTC
