### ISSUE TITLE
A total of 0 anchor was found. Aborted./lastal: I was installed here with multi-threading disabled

### ISSUE THREAD

**Issue by Fang777** [tanghaibao/jcvi#420] opened 2021-11-23 13:06 UTC
I run python -m jcvi.compara.catalog ortholog grape1 peach1 command, an error appeared:
[20:53:24] DEBUG    lastdb peach1 peach1.cds                        ]8;id=731755;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/apps/base.pybase.py]8;;:]8;id=307215;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/apps/base.py#11841184]8;;
[20:55:22] DEBUG    lastal -u 0 -P 2 -i3G -f BlastTab peach1 grape1.cds >./grape1.peach1.last                                     ]8;id=585476;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/apps/base.pybase.py]8;;:]8;id=460350;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/apps/base.py#11841184]8;;
lastal: I was installed here with multi-threading disabled
[20:55:24] DEBUG    Assuming --qbed=grape1.bed --sbed=peach1.bed                                                                ]8;id=609232;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.pysynteny.py]8;;:]8;id=298918;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.py#499499]8;;
           DEBUG    Load file `grape1.bed`                                                                                          ]8;id=878627;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.pybase.py]8;;:]8;id=855974;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py#3434]8;;
[20:55:25] DEBUG    Load file `peach1.bed`                                                                                          ]8;id=147262;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.pybase.py]8;;:]8;id=729854;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py#3434]8;;
           DEBUG    Load BLAST file `grape1.peach1.last` (total 0 lines)                                                     ]8;id=694182;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.pyblastfilter.py]8;;:]8;id=315629;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.py#4646]8;;
           DEBUG    Load file `grape1.peach1.last`                                                                                  ]8;id=565751;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.pybase.py]8;;:]8;id=953331;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py#3434]8;;
           DEBUG    running the cscore filter (cscore>=0.70) ..                                                             ]8;id=956554;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.pyblastfilter.py]8;;:]8;id=539751;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.py#108108]8;;
           DEBUG    after filter (0->0) ..                                                                                  ]8;id=355011;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.pyblastfilter.py]8;;:]8;id=293975;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.py#110110]8;;
           DEBUG    running the local dups filter (tandem_Nmax=10) ..                                                       ]8;id=192083;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.pyblastfilter.py]8;;:]8;id=812881;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.py#115115]8;;
           DEBUG    after filter (0->0) ..                                                                                  ]8;id=715426;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.pyblastfilter.py]8;;:]8;id=720060;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/blastfilter.py#155155]8;;
[20:55:26] DEBUG    Assuming --qbed=grape1.bed --sbed=peach1.bed                                                                ]8;id=603863;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.pysynteny.py]8;;:]8;id=76889;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.py#499499]8;;
           DEBUG    Load file `grape1.bed`                                                                                          ]8;id=762292;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.pybase.py]8;;:]8;id=189031;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py#3434]8;;
           DEBUG    Load file `peach1.bed`                                                                                          ]8;id=513758;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.pybase.py]8;;:]8;id=993514;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py#3434]8;;
[20:55:27] DEBUG    Load file `grape1.peach1.last.filtered`                                                                         ]8;id=577461;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.pybase.py]8;;:]8;id=380706;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py#3434]8;;
           DEBUG    A total of 0 BLAST imported from `grape1.peach1.last.filtered`.                                             ]8;id=421856;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.pysynteny.py]8;;:]8;id=51743;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.py#386386]8;;
           DEBUG    Chaining distance = 20                                                                                     ]8;id=164906;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.pysynteny.py]8;;:]8;id=328371;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.py#19311931]8;;
           DEBUG    Load file `grape1.peach1.anchors`                                                                               ]8;id=325686;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.pybase.py]8;;:]8;id=488124;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/formats/base.py#3434]8;;
           DEBUG    A total of 0 anchor was found. Aborted.                                                                    ]8;id=997705;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.pysynteny.py]8;;:]8;id=495321;file:///home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.py#14801480]8;;
Traceback (most recent call last):
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 947, in <module>
    main()
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 78, in main
    p.dispatch(globals())
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/apps/base.py", line 110, in dispatch
    globals[action](sys.argv[2:])
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/catalog.py", line 715, in ortholog
    scan(dargs)
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1948, in scan
    summary([anchor_file])
  File "/home/manager/miniconda3/envs/jcvi/lib/python3.9/site-packages/jcvi/compara/synteny.py", line 1481, in summary
    raise ValueError("A total of 0 anchor was found. Aborted.")
ValueError: A total of 0 anchor was found. Aborted.

I guess "lastal: I was installed here with multi-threading disabled" could be the reason, and how should I do?

**Comment by tanghaibao** [comment] 2021-11-23 15:55
@Fang777 

Can you try reinstalling LAST from here: https://gitlab.com/mcfrith/last?

**Comment by tanghaibao** [comment] 2022-03-08 07:32
Duplicate of #440

**Closed by tanghaibao** 2022-03-08 07:32 UTC
